### ISSUE TITLE
Enhancement: Multilingual README

### ISSUE THREAD

**Issue by dumblob** [svobodneslovniky/svobodneslovniky#1]
Did you consider maintaining multilingual (English and Czech, in this order) README? English version should bring way more popularity and interest of others (potential contributors).

**Comment by xHire** [comment]
Actually, I didn’t. I suppose, to maintain multilingual nature of this repository’s documentation, other files (like format*) would need the same care as READMEs, right? This also leads me to a question: what when we add dictionaries for more languages? Will English&Czech documentation suffice?

Could you give me an argument why Czech docs shouldn’t be enough for someone willing to contribute to a Czech dictironary? :c)

*) There isn’t the format file yet, but I’m about to commit it soon (although not before our discussion comes to a conclusion).

**Comment by dumblob** [comment]
Hi, sorry for the late answer (GitHub stopped sending me notifications few months ago because of email bouncing issues - now it works again and I'm digging through all the piles of stuff I didn't get notifications about).

The reason is simple. The dictionary will be (or probably already is) used in global applications (mobile/desktop/web dictionaries) and all these have user interfaces, documentation, etc. in English.

But of course, if you expect some contributors to contribute solely in non-English language (which is a nonsense by definition in this dictionary), the README and some other stuff might be also in the particular non-English language (**in addition** to the default English).

**Comment by xHire** [comment]
> But of course, if you expect some contributors to contribute solely in non-English language (which is a nonsense by definition in this dictionary)

Well, this project is not meant to be just an English-Czech dictionary, but *-Czech dictionaries.

It probably depends on what your point was: to add English texts, because the main (and currently only) dictionary is an English one or because English is a universal international language? To put it another way: would you argue differently if the main (and possibly only) dictionary was, e.g., German-Czech?

**Comment by dumblob** [comment]
>To put it another way: would you argue differently if the main (and possibly only) dictionary was, e.g., German-Czech?

No, I would argue exactly the same way. English shall be the default choice for README and other stuff in this project disregarding which dictionary it is. Also because this project acts as a "dictionary backend" (i.e. content) which is expected to be used on various places as backend ("dictionary data").

Even such a basic thing as referencing this dictionary in proposals for existing dictionary applications (e.g. for QuickDic [[1]](https://github.com/rdoeffinger/Dictionary ) [[2]](https://f-droid.org/wiki/index.php?title=de.reimardoeffinger.quickdic&redirect=no ) from F-Droid) is currently impossible :cry:.

**Comment by xHire** [comment]
Thank you for clarification as this was my initial confusion (I imagined maintaining many language versions of everything which just seemed insane ;c)). This way I have no objections and will add English version of README on its next update (which should happen soon as information in there is already outdated). As for the format file, that will be more challenging… I’ll probably go with two files not to make it too complicated (as soon as we’re done changing it in #18).

Thank you for your input!

**Comment by talaj** [comment]
Maybe could be enough to keep just English version for simplicity, maintainability.

**Comment by dumblob** [comment]
@xHire thanks for the great news. Feel free to close this issue once the change landed.

And sorry for not being clear enough right from the beginning.
