### ISSUE TITLE
MacOS verze slovníku

### ISSUE THREAD

**Issue by lzap** [svobodneslovniky/svobodneslovniky#107]
Ahoj, vybuildil jsem MacOS Dictionary.app kompatibilní verzi, vše včetně návodu je k dispozici na:

https://github.com/lzap/cesky-slovnik-macos

Napadlo mě to prolinkovat ze stránek https://www.svobodneslovniky.cz/ v sekci Jak je použít, ale nenašel jsem HTML kód stránky.

No každopádně díky, čauec!

**Comment by xHire** [comment]
Ahoj, to je pecka! Na stránky jsem zmínku s odkazem přidal. Díky moc! :·)

Mimochodem, zajímavý blog. :·)
