### ISSUE TITLE
Support attribution with more authors

### ISSUE THREAD

**Issue by strepon** [svobodneslovniky/svobodneslovniky#30]
V pátém sloupci je sice možné uvést víc autorů, ale při zpracování se s údajem pracuje jako s jedním řetězcem a v seznamu autorů je pro něj vytvořen samostatný záznam. Bylo by proto fajn domluvit se na nějakém oddělovači, který by se při vytváření seznamu autorů zohledňoval.

Napadlo mě to v souvislosti s tím, že občas nahrazuji víceslovný překlad jednoslovným a původní přesouvám do poznámky - pak by asi bylo správné ponechat i autora původního překladu, nerad bych ale, aby kvůli tomu neúměrně narůstal seznam autorů.

**Comment by xHire** [comment]
Souhlas, tohle je aktuálně nešikovně (ne)řešené.

Podíval jsem se na možnosti. V pátém sloupci jsou aktuálně využity následující znaky:

     "&'()+,-./0123456789:;<>@ABCDEFGHIJKLMNOPRSTVWXYZ[]_abcdefghijklmnopqrstuvwxyzáíöýČčěňřŠšťůŽž–

Z oddělovačů, které by se nabízely:
* `&` má někdo v pseudonymu
* `,` by byla nejlepší, ale M.Chromá ji má použitu celkem přirozeným způsobem
* `;` je použitý jednou, a to v souladu s návrhem ✓
* `/` by potenciálně také šlo ✓
* `+` také ✓
* `|` není použit vůbec ✓

Šel bych tedy osobně přes středník. Počáteční nasazení obnáší akorát drobnou úpravu při generování záhlaví + zanesení informace do formátu. Postupně by se mohly normalizovat existující víceautorské záznamy a potažmo záznamy, kdy jeden autor udělal ve svém jménu nějakou drobnou nerelevantní změnu (překlep, malé písmeno apod.).

**Comment by strepon** [comment]
Středník mi připadá jako nepřirozenější a nejvhodnější možnost, takže jsem rozhodně pro.
