### ISSUE TITLE
CI for PR

### ISSUE THREAD

**Issue by talaj** [svobodneslovniky/svobodneslovniky#5]
Bylo by fajn, kdyby formát a uspořádání slovníku při pull requestu kontroloval třeba Travis.

Rád se ujmu iniciativy.

**Comment by xHire** [comment]
To by bylo super. :c) Pár poznámek z mé strany:

Formát
------
Můžeme kontrolovat jednak jednoduše počet sloupců, druhak různé speciality. Mezi nimi třeba slovní druh, obor apod. (nepředpokládám, že teď jsou všechny záznamy takto validní, ale mít skript, tak jednoduše víme, které nejsou).

Specifikaci formátu (technicky přesázená kopie toho, co bylo na původním webu) bych měl brzy commitnout, jakmile si vyčistím repozitář od svých úprav (které také pošlu).

Uspořádání
----------
O tomhle problému jsme se bavili se Standou Horáčkem. Základní problém je, že nedává smysl řadit anglický i český sloupec stejným uspořádáním. A to nemluvím o případných dalších jazycích (které budou). Ideální by tedy bylo mít skript (pokud se vejdeme do standardních unixových utilit, tak jedině dobře), který by řazení provedl zvlášť pro anglický sloupec podle anglických zvyklostí a pro český podle našich.


Nicméně nemusí být implementované hnedka všechno od začátku. Každopádně řazení zrovna teďka moc nefunguje. Pro kontrolu počtu sloupců už tu lokálně awk skript mám. :c)

**Comment by strepon** [comment]
Určitě by stálo za to kontrolovat obsah třetího sloupce, zda spadá do množiny daných kategorií (slovní druh, obor). Obsah jsem si vyjel, když jsem snažil kategorie sjednocovat, a největší problém v současnosti představují gramatické údaje typu:
```
which	nichž	(gen/loc)pl.		
which	nimiž	(ins pl)		
which	nimž	(dat pl)		
which	niž	(f acc)		
which	něhož	(m/n acc/gen)		
which	nějž	(m acc)		
```
o kterých ani nevím, jestli tam mají co dělat - vztahují se k českému překladu v různých tvarech (které se jinak neuvádí), ne k originálu. 

Pokud bychom tohle eliminovali, zbudou řádově desítky kategorií, s nimiž by už šlo při kontrole pracovat.

**Comment by xHire** [comment]
> o kterých ani nevím, jestli tam mají co dělat

Pády IMHO nemají vůbec smysl a při nějaké další vlně čištění můžou přijít smazat. Většina běžných uživatelů stejně nebude schopna dekódovat latinské zkratky pádů.

Podobně přídavná jména pro jiný než mužský rod (samozřejmě až na výjimky – mám na mysli především to, když někdo k překladu s koncovkou -ý přidal ještě překlad -á/-é).

Konečně jsem přidal do repozitáře původní specifikaci formátu. Vím o tom, že ve slovníku jsou reálně i další kategorie – očekávám, že dříve nebo později otevřeme diskusi na téma, které přidat a které ne. U některých by nebylo zlé přidat i nějakou vysvětlivku (např. kdy použít `[ekon.]` a kdy `[fin.]`?).

**Comment by strepon** [comment]
Souhlasím, poznámky by měly popisovat anglický originál, ne český překlad (i když tomuto neodpovídají kategorie [male] a [female]).

Smysl asi nemají ani 3. osoby sloves (ty se vyskytují často), možná ani pravidelná množná čísla. Ale to je věc k budoucí diskusi, ne aktuální problém.

Po dalším čištění navrhnu rozšíření kategorií, mám v hlavě pár dalších... A ještě námět: nebylo by přehlednější seznam kategorií řadit tematicky a hierarchicky? (Např. v lingvistické části [fráz.], [slang.], [vulg.] apod., v přírodních vědách pod [bio.] ještě [bot.], [zoo.] a [med.] atp.)

**Comment by xHire** [comment]
`[male]` a `[female]` jsou hrozně nadužívané. Pokud nejde o vyloženě maskulinní/femininní slova/významy, tak bych to mazal (např. worker → dělník/dělnice :-1:).

Ad přepracování seznamu kategorií – jsem pro. Ať je to tak, aby se to dobře používalo.

**Comment by strepon** [comment]
Ono podle současného používání je [male]/[female] k dělník/dělnice správně, vztahuje se totiž k překladu, ne k "worker" - nicméně přehodnocení bych se nebránil.

Až budu mít konkrétní návrhy, otevřu pro ně nové issues/pull requesty.

**Comment by xHire** [comment]
Ano, takhle ano, špatně jsem se vyjádřil. Měl jsem na mysli zejména to, že tam ten druhý překlad vůbec je (takže smazat dělnici, a tím pádem i to `[male]` u dělníka). Osobně nevidím přínos toho, aby ve slovníku ke každému mužskému tvaru slova označující nějakou osobu byl i ženský. Takových slov jsou mraky (a slovník je v tomhle směru velmi neúplný – pro příklad mi stačí grepnout na výrazy „úředník“ vs. „úřednice“). S ohledem na to, jak angličtina funguje, tak to z mého pohledu význam nemá. Kategorie `[male]` a `[female]` bych viděl zejména tam, kde tohle pravidlo nefunguje a příslušné slovo by se v druhém rodě používat nemělo.

**Comment by talaj** [comment]
Issue se zřejmě zavřelo automaticky po začlenění https://github.com/xHire/svobodneslovniky/pull/8. Znovu bych jej otevřel. Ještě zbývá

- [ ] aktualizovat seřazení slovníku,
- [ ] zapnout testování na [travis-ci.org](https://travis-ci.org).

**Comment by xHire** [comment]
Zkoušel jsem zapnout travis, ale požadoval trochu nadměrnou množinu oprávnění k mému zdejšímu účtu, kterou nejsem úplně ochotný dát z ruky. Zkoumám alternativy.

**Comment by talaj** [comment]
Možná vytvořit github uživatele pro testování. Je to v souladu s [pravidly](https://developer.github.com/guides/managing-deploy-keys/#machine-users).

**Comment by xHire** [comment]
To je dobrý nápad, tak to udělám, díky za radu. :c)

**Comment by talaj** [comment]
Zkouším to, ale myslím, že bez vytvoření [organizace](https://github.com/organizations/new) to nepůjde. Nelze dát jinému uživateli dostatečná práva k osobnímu repozitáři.

**Comment by xHire** [comment]
Uff, to teda byla anabáze. Jak málo stačí k tomu, aby člověk začal travis nenávidět. –_– Ale je to zapnutý, tak snad to bude fungovat: https://travis-ci.org/svobodneslovniky/svobodneslovniky
