### ISSUE TITLE
Špatné nastavení SSL na serveru

### ISSUE THREAD

**Issue by nijel** [svobodneslovniky/svobodneslovniky#90]
Na aktuálním Debianu sid openssl odmítne připojení k serveru:

```
curl: (35) error:141A318A:SSL routines:tls_process_ske_dhe:dh key too small
```

Problém je v příliš krátkých parameterech pro výměnu klíčů Diffie-Hellman.

Jinak je tam spoustu dalších problémů, viz https://www.ssllabs.com/ssltest/analyze.html?d=www.svobodneslovniky.cz&s=83.167.252.118

**Comment by xHire** [comment]
Vyřešeno, díky za upozornění! :·) Když jsem to viděl, tak jsem se zděsil, hluboce zastyděl, pomyslel cosi o jistém kováři a dal se do nápravy.
